name: Deploy Backend

on:
  push:
    branches: [ "server" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build JAR
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          ls -al build/libs

      - name: Upload JAR & Dockerfile to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/libs/*.jar,Dockerfile"
          target: "~/server/backend/"
          strip_components: 0

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "ğŸš€ Start Deploy..."

            cd ~/server/backend

            echo "ğŸ›‘ Stop old backend container"
            docker stop backend || true
            docker rm backend || true

            echo "ğŸ³ Build Docker image"
            docker build -t backend .

            echo "â–¶ Run new backend container"
            docker run -d -p 8080:8080 --name backend backend

            echo "ğŸ‰ Deploy Completed!"
